### ISSUE TITLE
TITLE: RUBY CAPSTONE PROJECT KANBAN

### ISSUE THREAD

**Issue by kendoriddy** [DuaneDave/Catalog-of-my-things#32]
- The link to our capstone project is [here](https://github.com/DuaneDave/Catalog-of-my-things).
- This team comprises of three members.
- @DuaneDave is TEAM MEMBER 1
- @kendoriddy is TEAM MEMBER 2
- @username-forGithub is TEAM MEMBER 3

**Comment by Omar-Muhamad** [comment]
# Changes Required ♻️
### Hi @kendoriddy, @DuaneDave, and @username-forGithub,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Changes Required) Aspects to improve: ♻️

- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#:~:text=Has%20a%20description%20of%20the%20task.), Please make sure that all kanban cards have a proper description to each card.

![image](https://user-images.githubusercontent.com/68796232/201731748-0217ae55-5ba3-4dd8-8873-5062455ed542.png) 

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by kendoriddy** [comment]
Thanks for your feedback @Omar-Muhamad. The necessary corrections have been made.

- The link to our capstone project is [here](https://github.com/DuaneDave/Catalog-of-my-things).
- This team comprises of three members.
- @DuaneDave is TEAM MEMBER 1
- @kendoriddy is TEAM MEMBER 2
- @username-forGithub is TEAM MEMBER 3

**Comment by andersonlebon** [comment]
### Hello @kendoriddy, @DuaneDave, and @username-forGithub  
Your project is complete!  There is nothing else to say :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 

- Good PR description :heavy_check_mark:  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------

**Comment by HAMMAS-SALEEM** [comment]
# Invalid Pull Request :red_circle:

## Hey Team :wave:

## Highlights :1st_place_medal:

✔️ Descriptive Issue Title
✔️ Descriptive Issue Summary
✔️ Following Kanban Board
✔️ Following some requirements

Good job on implementing some of the reqirements, But i cannot proceed review on your project there are some issues that you still need to work on :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

## :arrow_right: Changes :recycle:
- [ ] I can see that this project has been approved last week but this week you have a different team so kindly make a new repo with a new kanban board with a new team :+1:
